### ISSUE TITLE
api.get_resource('/routing/bgp/session') - connection timeout

### ISSUE THREAD

**Issue by traxinv** [edgenative/mikrotik-bgpmon#2]
Hi - I am trying to set this up to connect to mikrotik CCR2216-1G-12XS-2XQ.

I see on the router side the connection come in and disconnect but i get the following error:

_

> Traceback (most recent call last):
>   File "..\Python\Python312\site-packages\routeros_api\base_api.py", line 31, in receive_sentence
>     return list(iter(self.receive_word, b''))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "..\Python\Python312\site-packages\routeros_api\base_api.py", line 38, in receive_word
>     expected_length = decode_length(self.socket.receive)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "..\Python\Python312\site-packages\routeros_api\base_api.py", line 74, in decode_length
>     first = ord(read(1))
>                 ^^^^^^^
>   File "..\Python\Python312\site-packages\routeros_api\api_socket.py", line 72, in receive
>     return self._receive_and_check_connection(length)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "..\Python\Python312\site-packages\routeros_api\api_socket.py", line 80, in _receive_and_check_connection
>     bytes = self.socket.recv(length)
>             ^^^^^^^^^^^^^^^^^^^^^^^^
> TimeoutError: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "..\mikrotik-bgpmon-1.0.1\mikrotik_bgpmon_print.py", line 44, in <module>
>     current_config_response = current_config_connection.get()
>                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "..\Python\Python312\site-packages\routeros_api\resource.py", line 7, in get
>     return self.call('print', {}, kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "..\Python\Python312\site-packages\routeros_api\resource.py", line 39, in call
>     additional_queries=additional_queries).get()
>                                            ^^^^^
>   File "..\Python\Python312\site-packages\routeros_api\resource.py", line 85, in get
>     response = self.inner.get()
>                ^^^^^^^^^^^^^^^^
>   File "..\Python\Python312\site-packages\routeros_api\api_communicator\encoding_decorator.py", line 31, in get
>     response = self.inner.get()
>                ^^^^^^^^^^^^^^^^
>   File "..\Python\Python312\site-packages\routeros_api\api_communicator\async_decorator.py", line 17, in get
>     self.response = self.receiver.receive(self.tag)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "..\Python\Python312\site-packages\routeros_api\api_communicator\exception_decorator.py", line 19, in receive
>     self.handle_exception(e)
>   File "..\Python\Python312\site-packages\routeros_api\api_communicator\exception_decorator.py", line 37, in handle_exception
>     raise exception
>   File "..\Python\Python312\site-packages\routeros_api\api_communicator\exception_decorator.py", line 17, in receive
>     return self.inner.receive(tag)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "..\Python\Python312\site-packages\routeros_api\api_communicator\key_cleaner_decorator.py", line 14, in receive
>     answers = self.inner.receive(tag)
>               ^^^^^^^^^^^^^^^^^^^^^^^
>   File "..\Python\Python312\site-packages\routeros_api\api_communicator\base.py", line 46, in receive
>     response_buffor_manager.step_to_finish_response()
>   File "..\Python\Python312\site-packages\routeros_api\api_communicator\base.py", line 130, in step_to_finish_response
>     self.receiver.process_single_response()
>   File "..\Python\Python312\site-packages\routeros_api\api_communicator\base.py", line 59, in process_single_response
>     response = self.receive_single_response()
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "..\Python\Python312\site-packages\routeros_api\api_communicator\base.py", line 65, in receive_single_response
>     serialized = self.base.receive_sentence()
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "..\Python\Python312\site-packages\routeros_api\base_api.py", line 33, in receive_sentence
>     raise exceptions.RouterOsApiConnectionError(str(e))
> routeros_api.exceptions.RouterOsApiConnectionError: timed out

_

**Comment by edgenative** [comment]
Do you have the API enabled on your router? That's telling you it's timing out - it's not just the web interface that needs to be reachable but also the API

**Comment by traxinv** [comment]
HI - yes API is enabled and the program does log in but when it tries to retrieve the bgp session details:
current_config_connection = api.get_resource('/routing/bgp/session')
current_config_response = current_config_connection.get()

PS: i have 105 session :)

![image](https://github.com/edgenative/mikrotik-bgpmon/assets/3995322/1e8ee1db-dfbc-41d6-a3e9-fa166c80e521)
![image](https://github.com/edgenative/mikrotik-bgpmon/assets/3995322/a66a3cbe-a011-4db1-b772-0e48a74d2712)

**Comment by edgenative** [comment]
The number of sessions are no problem -- I had it checking a box with well over 200 at one point.

The screenshots are helpful, you need the API enabled on SSL (I'll update the docs to make that more obvious!).  If you see on line 67 of mikrotik_bgpmon.py, it's got: use_ssl=True.  You can modify this if you don't want to run your API on SSL, or setup your API to be enabled on SSL (self-signed cert is fine).

**Comment by traxinv** [comment]
HI sorry - i might not have specified that i did change the RouterOsApiPool params:

![image](https://github.com/edgenative/mikrotik-bgpmon/assets/3995322/9efd115f-aab0-42d4-8f42-c30d396ce6c9)

**Comment by edgenative** [comment]
I've never tried it without SSL I'm afraid, so unsure what the issue could be there.  I'm not using Mikrotik at the moment, so if I get a chance in the next few days I'll fire one up and give it a try -- but quickest is to enable SSL on the router, or take a look at the documentation for the python library and see what you can figure out.

**Comment by traxinv** [comment]
no problem - let me jump through the code and see

**Comment by edgenative** [comment]
Did you ever figure it out?
